id: a342608375094f88a01abf5c63e8f038
initial_creation_type: ocr
source_metadata:
  volumes:
    75bc9543b7ef4a2f94db0dda2a0d6f04:
      base_file: v026.txt
      image_group_id: I1PD95871
      title: ''
      total_pages: 1902
      volume_number: 26
